### PR TITLE
Introduce Vision API

### PR DESCRIPTION
**Pull request by belaszalontai**
Based on this doc https://platform.openai.com/docs/guides/vision without proper API reference

### CODE REVIEW

**Comment by belaszalontai** [comment]
@kayhantolga PLease review. Unfortunately so far there is no clear API reference for Vision feature at open AI's docs. Only a general guide exists. 

Here are some confusing point:
- the content of a Message in messages is different for ChatCompletion with normal models and chat completion with vision model. For normal models it is a string type, for vision model it is a json array type with more content. Maybe it could be used mixed but I decided in this implementation to implement only the json array for vision model.
- FromAssistant (Assistant role) is available but for what?
- should I implement some helper for base64 encoding? If yes where should I placed in the code?

**Comment by belaszalontai** [comment]
meanwhile I have realized that there is an API description for chat completion which defines the type of content for Vision API here: https://platform.openai.com/docs/api-reference/chat/create

Acoording to this reference, the
- System, Assistant message can only be string
- User message can be string or array

So I am refactoring this PR..

**Comment by hucongquan** [comment]
Hello，
你发的邮件我已经收到啦，Thx！

**Comment by belaszalontai** [comment]
New PR will be placed soon

**Pull request closed without merging**
