### PR TITLE
Added support for the new function calling capability in Chat Completions API

### PR DESCRIPTION
**Pull request by rzubek**
Hi there!

Here's a PR that adds support for new function calling capability in GPT 
https://openai.com/blog/function-calling-and-other-api-updates

Includes 
- Data model for function definitions in the request, and parsing out function calls in the reply
- Test function that illustrates usage
- Model definitions for 0613 updates which are the min version for this API

Does not include changes to documentation (like the readme file), not sure what's the best place to document this.

### CODE REVIEW

**Comment by rzubek** [comment]
It's worth noting that this functionality is not compatible with streaming completions API.

If a chunked response contains a function call, the call gets split up just as if it were a message (on whitespace, from the looks of it), and the function name and arguments are returned as separate chunks. And then CreateCompletionAsStream() gets those multiple chunks, but is unable to put that back together because it's not the message being split.

It's not clear that splitting up function calls was intended behavior on their end - it makes it difficult to put the result back together. Maybe we put up a warning if we detect that the user is trying to use a streaming function, and they have the Functions list populated?

**Comment by oferavnery** [comment]
I hope it does work in streaming as the stream does include the function output - just need to parse it differently. If streaming doesn't support functions we won't be able to use the API :(

**Comment by rzubek** [comment]
It was an unexpected bit of work, but I added support for streaming.

During stream processing we detect if a function call is being returned, and if so, a separate handler starts accumulating function call data, and then returns it as one packed when it's done.

I don't think there's a way around this kind of an accumulator, because the whole function call JSON needs to be collected before it can be passed anywhere else (e.g. to a JSON parser).

Feedback appreciated!

**Comment by rzubek** [comment]
By the way, for anyone interested, this is what a streamed function call looks like:

Unstreamed: 
```json
{..."choices":[{"index":0,"delta":{"role":"assistant","content":null,"function_call":{"name":"get_n_day_weather_forecast","arguments":"{\n  \"location\": \"Chicago, USA\",\n  \"format\": \"F\",\n  \"num_days\": 5\n}"}},"finish_reason":"function_call"}]}
```

Streamed:
```json
{..."choices":[{"index":0,"delta":{"role":"assistant","content":null,"function_call":{"name":"get_n_day_weather_forecast","arguments":""}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"{\n"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" "}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" \""}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"location"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"\":"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" \""}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"Chicago"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":","}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" IL"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"\",\n"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" "}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" \""}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"format"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"\":"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" \""}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"C"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"elsius"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"\",\n"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" "}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" \""}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"num"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"_days"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"\":"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":" "}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"5"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"\n"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{"function_call":{"arguments":"}"}},"finish_reason":null}]}
{..."choices":[{"index":0,"delta":{},"finish_reason":"function_call"}]}

```

**Pull request merged**
