### PR TITLE
Add GPT-4-Turbo/Vision + Updated GPT-3.5-Turbo models

### PR DESCRIPTION
**Pull request by ChaseIngersol**

### CODE REVIEW

**Comment by tylerje** [comment]
In addition to the models, I'd love to see the "response_format" and "seed" properties added to the ChatCompletionCreateRequest class in order to use these new features. That may require some conditional code to allow it only for those models that support it if that is the case.

**Comment by ChaseIngersol** [comment]
I've added the `response_format` and `seed` properties to `ChatCompletionCreateRequest` but will need a bit of time to look into which models support these, as I can't find a clear answer yet in the docs. May require some testing on my part.

**Comment by tylerje** [comment]
> I've added the `response_format` and `seed` properties to `ChatCompletionCreateRequest` but will need a bit of time to look into which models support these, as I can't find a clear answer yet in the docs. May require some testing on my part.

Cool. I'll do some digging to see if I can help.

**Comment by ChaseIngersol** [comment]
Looks like `response_format` is only compatible with `Gpt_4_1106_preview` and `Gpt_3_5_Turbo_1106` from my testing. `seed` however is compatible with all GPT models. 

I will look into implementing conditional logic for incompatible models in both cases.. Would the preferred approach to be throw an exception informing the user that the model is incompatible with this property? 

I also added a `ResponseFormat` class for convenience so that the usage would be like so:

```
		var completionTask = openAiService.ChatCompletion.CreateCompletion(new ChatCompletionCreateRequest {
			Messages = new List<ChatMessage> {
				ChatMessage.FromSystem(systemMessage),
				ChatMessage.FromUser(prompt)
			},
			Model = model,
			Temperature = temperature,
			ResponseFormat = new ResponseFormat { Type = "json_object" }
		}, null, cancellationToken);
```

**Comment by zxrohex** [comment]
> Looks like `response_format` is only compatible with `Gpt_4_1106_preview` and `Gpt_3_5_Turbo_1106` from my testing. `seed` however is compatible with all GPT models.
> 
> Incompatible models return an `Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.` message as the response.
> 
> Is conditional logic still necessary in this case? If so, would the preferred approach be to throw an exception informing the user that the model is incompatible with this property?
> 
> I've also added a `ResponseFormat` class for convenience so that the usage would be like so:
> 
> ```
> var completionTask = openAiService.ChatCompletion.CreateCompletion(new ChatCompletionCreateRequest {
> 	Messages = new List<ChatMessage> {
> 		ChatMessage.FromSystem(systemMessage),
> 		ChatMessage.FromUser(prompt)
> 	},
> 	Model = Models.Gpt_4_1106_preview,
> 	Temperature = 0.8f,
> 	ResponseFormat = new ResponseFormat { Type = "json_object" }
> }, null, cancellationToken);
> ```

I mean, the FunctionCall property in ChatMessage is always defined too and throws a exception if it's null, which is literally all of the time except when GPT is calling a function, which is the property's sole reason for existing, so I don't see why doing it in an different way, the library mainly uses defined properties that throw an exception if it's not needed unless the sole existence of the property makes difficulties

**Comment by tylerje** [comment]
>>ResponseFormat { Type = "json_object" }

Why not make this an enum with two values:

Unspecified (default)
JsonObject

My reasoning is there is likely to be additional format types in the future.

**Review by kayhantolga — APPROVED** [review]

**Comment by kayhantolga** [comment]
I made some changes, if everyone is happy I will merge this tomorrow.

**Comment by kayhantolga** [comment]
I messed up a bit with resolving merge conflicts (actually, I blame Visual Studio). Please let me know if you see something odd.

**Comment by Puresoft** [comment]
Hi, is there a workaround for response_format until this gets into the master branch?

**Pull request merged**
