### PR TITLE
Addition of new GPT3-Turbo and GPT4 models

### PR DESCRIPTION
**Pull request by Alerinos**
I added two new models that came out in the last update. 

https://openai.com/blog/function-calling-and-other-api-updates

### CODE REVIEW

**Comment by itsmuntadhar** [comment]
Would be better having the `functions` array added to `ChatCompletionCreateRequest`

**Comment by Alerinos** [comment]
> Would be better having the array added to `functions``ChatCompletionCreateRequest`

The ``Model`` cannot be defined by an object, it must be a string. That's because in case of an update like now, you can manually name the new model and you can have your own models that you have taught.

**Comment by itsmuntadhar** [comment]
already changed it. I meant to add a new property in the dto

**Comment by kayhantolga** [comment]
I have to close this PR. Adding support for new models has been addressed in a different PR. Thank you for contributing.

**Pull request closed without merging**
