### PR TITLE
Handle cancellation token in existing endpoints

### PR DESCRIPTION
**Pull request by robertlyson**
This PR address GH-90.
Let me know what you think, hope I didn't miss a bit.

### CODE REVIEW

**Comment by kayhantolga** [comment]
looks simple and clean 👍🏻 
I will have look one more time when I have a time. It would be nice if we can create one  simple test at playground.

Could you please target dev branch instead of master?

**Comment by robertlyson** [comment]
Thanks for the comment @kayhantolga! Switched branch to dev and prepared one example with cancellation token.

**Comment by kayhantolga** [comment]
hey @robertlyson, I just ran my ReSharper for general code cleanup. I also noticed token cancellation wasn't working with stream API. So I made some changes there. Now it works. If you approve my changes I will merge this PR.

**Comment by robertlyson** [comment]
@kayhantolga good job with spotting issue with while loop :+1:. Looks good to me.

**Comment by robertlyson** [comment]
Actually just realized that we should do `token.ThrowIfCancellationRequested()` instead of `if (cancellationToken.IsCancellationRequested)` inside while loop, otherwise task won't be marked as cancelled. Let me know what you think @kayhantolga.

**Comment by kayhantolga** [comment]
I didn't like the fact that we have to use another try catch but as much as I understand the design pattern suggests throwing an exception. I  just updated the code. all good?

**Comment by robertlyson** [comment]
@kayhantolga all good. Thank you for all of the fixes you have put in 🙏

**Pull request merged**
