### PR TITLE
Implement support for Embeddings API 

### PR DESCRIPTION
**Pull request by sarilouis**

### CODE REVIEW

**Comment by kayhantolga** [comment]
Thanks for creating PR. The only issue I have noticed was possible null reference exceptions in SingleOrArrayConverterFactory. I have tried to fix them but there is still one exist I wasn't sure how to handle it. Please have a look => line 58 itemtype, `converterType = typeof(SingleOrArrayConverter<,>).MakeGenericType(typeToConvert, itemType);`
If you think it is okay we can merge the PR.

**Comment by kayhantolga** [comment]
Oh, also can you target to dev branch please, I would like to push couple more changes before master merge.

**Comment by sarilouis** [comment]
Hi Tolga,

I just changed the target to the Dev branch. Apologies, this is the first time I contribute directly to an open source project, so please bear with me if I mess things up in the process.

As for SingleOrArrayConverterFactory, it was something I had used on another project where the server changed based on the count and I needed to properly deserialize to the POCOs. However, with OpenAI the server always returns an array, so really this is only saving a couple of brackets from being sent in the request in the case of a single string.

So, in hindsight, I don't think it's worth the complexity and potential edge-case bugs and I would rather just drop it completely.

**Comment by kayhantolga** [comment]
Hi,
This is my first time managing an open-source project, so we are both new in the area. I should have updated the document about PR.
I think the main difference in this project from yours is the nullable setting is enabled. 
`OpenAI.GPT3.csproj line:6` -> `<Nullable>enable</Nullable>`
I think it would be better if we use just an array. I would appreciate it if you can drop SingleOrArrayConverterFactory and use array.

**Comment by sarilouis** [comment]
Sounds good. I dropped it and committed. I think everything is in order at this point

**Comment by kayhantolga** [comment]
Great, Thanks! I will release a new version soon with a couple of my changes.

**Comment by sarilouis** [comment]
Sounds good. Thanks a million for all the work you've done on this.

BTW, I had made other changes locally to the Completions API. Since they were breaking changes, I wasn't sure how best to handle and just didn't create a pull request for them. I just committed them to a new branch on my repo: https://github.com/sarilouis/openai/tree/update-completions. Not sure how you'd feel about them, but happy to discuss.

**Comment by sarilouis** [comment]
Oh and unrelated, but I also created a C# version of the GPT3 encoder/tokenzier if you might need it: https://github.com/sarilouis/GPT3Encoder-dotnet

**Comment by kayhantolga** [comment]
I was thinking of updating the usage of methods in general(also probably breaking changes.). 
I think I will have time next week. I will have a look at your changes and we can discuss them later.

**Pull request merged**
