### PR TITLE
readme edits / combo test / html builder / command-line

### PR DESCRIPTION
**Pull request by gotmike**
first pull request here. lmk if any changes are needed.

this one includes:
1. typo and addition for clarity to readme.md
2. addition of "combo test" that takes output from completion and sends to dall-e
3. combo test builds an html file and opens in default browser, makes it easier for user to see combined results (no copy/paste multiple urls)
4. takes prompt and number of images as command-line inputs, also added sample values to launchsettings.json

### CODE REVIEW

**Comment by kayhantolga** [comment]
Hi, I think the readme updates are okay. But I am not sure about combo tests and arguments in the playground. They increase complexity, especially for beginners. As I mentioned earlier I think it is better to keep it simple.

My suggestion is to create a new repo and we can point your sample projects on the wiki page. What do you think?

**Comment by gotmike** [comment]
up to u. imho, when trying to "take it for a test drive" it's nice to be able to have something that's easy to see the results.

also, nice to demonstrate the functionality of the tools working together.

but yeah i can roll on my own if that's preferable.

do i need to cancel and re-submit just those readme edits?

**Comment by gotmike** [comment]
i mean dunno if it's even worth a pr for the readme edits, they are very minor. can prob make those just copy/paste.

just lmk.

**Comment by gotmike** [comment]
so do u want me to re-submit and do a PR on just the readme edits?

**Comment by kayhantolga** [comment]
I am sorry, I was busy a bit if it is not too much hassle for you, yes, please 🙏🏻 .

**Comment by gotmike** [comment]
ok sure, i closed this PR and added new one --> https://github.com/betalgo/openai/pull/88

**Pull request closed without merging**
