### PR TITLE
Re-added the beta assistants API

### PR DESCRIPTION
**Pull request by CongquanHu**
Based on the latest changes to the library, I added APIs related to assistants to make PR merging easier.
1.Added beta assistants API (mostly)
2.The APIs used in the assistants demo flow were tested

### CODE REVIEW

**Comment by CongquanHu** [comment]
@kayhantolga

**Comment by CongquanHu** [comment]
I'm done. Please let me know if there is anything wrong.

**Comment by dmki** [comment]
Typo: Inst**ur**ctions
Also, can you replace Chinese with English, please?

**Comment by CongquanHu** [comment]
> Typo: Inst**ur**ctions Also, can you replace Chinese with English, please?

Thank you for reminding me.
I have changed the Chinese content of Instructions into English in the last commit.
image
image

**Comment by giovanni-a** [comment]
Thanks for this PR! I tested it, it works great! Small typo here: "StaticValues.AssistatntsStatics" instead of "StaticValues.AssistantsStatics"

**Comment by CongquanHu** [comment]
> Thanks for this PR! I tested it, it works great! Small typo here: "StaticValues.AssistatntsStatics" instead of "StaticValues.AssistantsStatics"

Thank you for reminding me. It's fixed.

**Comment by JKetelaar** [comment]
Any update on this?

**Pull request merged**
