### PR TITLE
Correct misspell in documentation

### PR DESCRIPTION
**Pull request by KosmonikOS**

### CODE REVIEW

**Comment by kayhantolga** [comment]
Hah, I have used, the biggest font size and made this simple mistake 🤦🏻 . Thanks for spotting this. Could you change your pull requests to target the dev branch, please(other prs too)?

**Comment by KosmonikOS** [comment]
No problems. Is it ok now ?

**Comment by djvictor88** [comment]
KosmonikOS:fix/documentation

**Comment by djvictor88** [comment]
KosmonikOS:fix/documentation

**Pull request merged**
