### PR TITLE
Ignore lines that start with : ping 

### PR DESCRIPTION
**Pull request by gavi**
When testing the client with streaming chat, I noticed the JSON parser crashes for lines that start at with ": ping", I believe its because the api sends chunks with event: ping which needs to be ignored

### CODE REVIEW

**Comment by kayhantolga** [comment]
I I didn't notice such a thing before. Do you think this is new behavior? Do you have any sample code or prompt?

**Comment by kayhantolga** [comment]
I I didn't notice such a thing before. Do you think this is new behavior? Do you have any sample code or prompt?

**Comment by gavi** [comment]
I was using the client with text-generation-webui openai plugin  and noticed the crash. Then I checked the official python implementation from openai and saw the ping messages in their [src/test_streaming.py](https://github.com/openai/openai-python/blob/15488ce07cb97535d8564e82dd5cda3481bc1a81/tests/test_streaming.py#L4)

**Comment by kayhantolga** [comment]
I have made some updates. I thought that maybe someone might find this data useful, so I kept it as optional.

Could you test my implementation to see if it helps? I couldn't test it because I don't have any prompts to trigger `pings`. I would greatly appreciate it if you could share one with me.

**Pull request merged**
