### PR TITLE
Add Text To Speech (tts-1) feature

### PR DESCRIPTION
**Pull request by belaszalontai**
Add Text To Speech feature based on the API ref: https://platform.openai.com/docs/api-reference/audio/createSpeech

### CODE REVIEW

**Comment by belaszalontai** [comment]
I am not 100% sure that the implementation of handling CreateSpeechResponse is proper. Please review. Can be tested in the playground too.

**Comment by kayhantolga** [comment]
Thanks for the PR, I will do a code review as soon as possible.

**Comment by kayhantolga** [comment]
@belaszalontai @szabe74 I made some updates, please have a look.

**Comment by belaszalontai** [comment]
Thnx to made it generic + introduced stream. This was what I wasn't shure about. 
From my side its reviewed and OK.

**Comment by MartinKlepal** [comment]
Hi, I have tried the the CreateSpeech yesterday and the mp3 created was always cut off at the end (last 30%), regardless of the lenght of the input text (if was always the last about 20-30%). I tried both stream or byte[] with the same result.
Any suggestion? Thanks.

part of my code based on your unit test example:

                var audioResult = await openAiService.Audio.CreateSpeech<byte[]>(new AudioCreateSpeechRequest
                {
                    Model = Models.Tts_1,
                    Input = "Helow",
                    Voice = StaticValues.AudioStatics.Voice.Nova,
                    ResponseFormat = StaticValues.AudioStatics.CreateSpeechResponseFormat.Mp3,
                    Speed = 1.0f
                });

                if (audioResult.Successful)
                {
                    var audio = audioResult.Data!;
                    await using var fileStream = File.Create($"{location}\\Resources\\recording.mp3");
                    await File.WriteAllBytesAsync($"{location}\\Resources\\recording4.mp3", audio);
                }

**Comment by belaszalontai** [comment]
@MartinKlepal I have downloaded your zipped mp3 files and listened. It looks fine. All sentence is spoken.
Please try it with another mp3 player.

**Comment by MartinKlepal** [comment]
> @MartinKlepal I have downloaded your zipped mp3 files and listened. It looks fine. All sentence is spoken. Please try it with another mp3 player.

you are absolutely right, I did not even think about it. I used the lates version of VLC medial Player. 
Sorry for my earlier post, which I deleted already. 
 And thanks you for your very good work on the betalgo openia

**Pull request merged**
