### PR TITLE
Extend Chat API with Vision feature

### PR DESCRIPTION
**Pull request by belaszalontai**
Introduce Vision feature extending the Chat Completion API.

- Chat Completions and Vision is Tested.
- Readme is updated
- it contains a possible breaking change: In ChatMessage.cs in the ChatMessage model the constructor have been removed because of a calculated json property. (System.Text.Json has limitations)

### CODE REVIEW

**Comment by kayhantolga** [comment]
hi, could you update the target branch as dev branch, please?

**Comment by belaszalontai** [comment]
Conflict has been resolved manually..

**Review by kayhantolga — APPROVED** [review]

**Comment by kayhantolga** [comment]
The last merge to the dev branch caused some merge conflicts. I synchronized the dev branch and resolved the merge conflicts. I also renamed the "VisionContent" class to "MessageContent". I believe that OpenAI will allow us to pass different types of contents, so I think the new name is future-proof. Please let me know if you have any notes on my changes. I will be merging this PR but I am happy to discuss any changes that you don't like.

**Comment by belaszalontai** [comment]
@kayhantolga thnx for findings and resolution. I don't understand the merge conflicts but it does not matter anymore :)

**Pull request merged**
