### PR TITLE
Assistant API

### PR DESCRIPTION
**Pull request by alistein**
### Creating AssistantEndpoint Providers for both OpenAI and AzureOpenAI endpoints
- Adding endpoints to IOpenAiEndpointProvider.cs interface
- Implement those endpoints in OpenAiEndpointProvider.cs and AzureOpenAiEndpointProvider.cs
- Creating Query parameters for Listing Assistant and Assistant Files in AssistantListRequest.cs
- Logic for Appending those query parameters to endpoint providers

### CODE REVIEW

**Comment by alistein** [comment]
> @alistein Do you plan to add Threads, Messages and Runs related endpoints in separated PRs or would you like to introduce the whole Assistant API under this PR?

@belaszalontai  This pr will be only for assistant api not whole one.

**Comment by kayhantolga** [comment]
hi, could you update the target branch as dev branch, please?

**Comment by kayhantolga** [comment]
Same feature merged in different PR. Thanks everyone whoever supported this branch 🙌🏻

**Comment by hucongquan** [comment]
Hello，
你发的邮件我已经收到啦，Thx！

**Pull request closed without merging**
